version: "3"

# サービス定義の一覧
services:
  # サービス1
  db:
    # MySQLを使用
    image: mysql:8.0
    # MySQLの認証形式の設定
    command: --default-authentication-plugin=mysql_native_password
    # ローカルとコンテナでファイルを共有する
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    # 環境変数の設定：DB接続時のパスワード
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  # サービス2
  web:
    # Baseイメージとしてドッカーファイルを使用する事を指定
    build: .
    # railsのサーバーを起動している
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # ローカルとコンテナのファイル共有の設定
    volumes:
      - ./src:/app
    # Portのバインド設定（ローカルの3000番とコンテナの3000番を接続）
    ports:
      - "3000:3000"
    # DBを名前で接続できるようにする
    depends_on:
      - db
    